spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/greenbyme
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000
        #one-indexed-parameters: true # 1부터 시작하게 함 하지만 가급적 0부터 시작하게한다.
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
logging:
  level:
    org:
      hibernate:
        type: trace
cloud:
  aws:
    credentials:
      accessKey: AKIASIF6HADX54Q5SKIE
      secretKey: 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
    s3:
      bucket: springboot2-build-book
    region:
      static: ap-northeast-2
    stack:
      auto: false
---
spring.profiles: dev
spring.profiles.include: real

