spring:
  profiles:
    active: dev

---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/greenbyme
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

#security:
#  basic:
#    enabled: false
logging:
  level:
    org:
      hibernate:
        type: trace

---
spring.profiles: dev
spring.profiles.include: real