spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/greenbyme
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
security:
  jwt:
    token:
      secret-key: 2020angelhackseoul
      expire-length: 3600000
#security:
#  basic:
#    enabled: false
logging:
  level:
    org:
      hibernate:
        type: trace
---
