spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/greenbyme
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.SQL: debug
---
spring.profiles: dev
spring.profiles.include: real